### PR TITLE
Respond to system theme on iOS

### PR DESCRIPTION
**Pull request by david-shortman**
- Changes keyboard color depending on system theme

Possible enhancements
- Could also take in a parameter for the `showKeyboard` method that allows for a dev to provide the desired keyboard color
- I didn't test with Android to see if this feature should also be implemented there

### CODE REVIEW

**Comment by JayPerfetto** [comment]
+1 this should be included

**Comment by david-shortman** [comment]
@mcrovero Is this an acceptable change? If you think either of the enhancements I listed are necessary for a merge, let me know.

Otherwise, since this repo hasn't been published to pub for a while anyway, I was thinking of publishing my fork to pub for now and continuing the project from there.

**Comment by mcrovero** [comment]
Hi, I've been pretty busy lately. I think the merge is great, as I won't be able to work on this for another while, would you like to have merge and publish permissions?

**Comment by david-shortman** [comment]
@mcrovero sure, I can help monitor this repo and review PRs. Thanks!

**Comment by mcrovero** [comment]
If you'd like to directly publish to pub.dev write me your email :) 
In the meanwhile many thanks, I really appreciate your help

**Comment by britannio** [comment]
The IOS keyboard color is configured by the `primaryColorBrightness` attribute in `ThemeData`. Does this override/break it? Users could select a dark mode when their system theme is light.
@david-shortman @mcrovero @JayPerfetto

**Comment by david-shortman** [comment]
@britannio you make a good point. As is, the keyboard will only respond to the system theme.

I think the best solution would be to give `brightness` as an attribute to the keyboard widget to allow the developer to control the scenario of how the keyboard should appear.

Doing this is something I probably won't be able to look at for a few weeks, so I can't make any promises.

**Pull request merged**
