### PR TITLE
update deprecated variable names in new Swift versions

### LINKED ISSUE #13: Package is not updated to work with new swift version...
The package seems to be using deprecated variable names in new Swift versions. When I try to use it in my project I get the following output : 
```
Failed to build iOS app
Error output from Xcode build:
↳
    ** BUILD FAILED **


Xcode's output:
↳
    /Users/moazelshebly/flutter/.pub-cache/git/plugins-d8860858d79b29c6777fe4bc9cf33359a3e7f77f/packages/share/ios/Classes/FLTSharePlugin.m:127:26: warning: variable 'originRect' may be uninitialized when used here [-Wconditional-uninitialized]
                    atSource:originRect];
                             ^~~~~~~~~~
    /Users/moazelshebly/flutter/.pub-cache/git/plugins-d8860858d79b29c6777fe4bc9cf33359a3e7f77f/packages/share/ios/Classes/FLTSharePlugin.m:107:5: note: variable 'originRect' is declared here
        CGRect originRect;
        ^
    1 warning generated.
    Command CompileSwift failed with a nonzero exit code
    Command CompileSwift failed with a nonzero exit code
    /Users/moazelshebly/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_interactive_keyboard-0.1.3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:18:114: error: 'keyboardWillShowNotification' has been renamed to 'NSNotification.Name.UIKeyboardWillShow'
            NotificationCenter.default.addObserver(self, selector: #selector(self.handleKeyboard), name: UIResponder.keyboardWillShowNotification, object: nil)
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                     NSNotification.Name.UIKeyboardWillShow
    UIKit.UIResponder:3:22: note: 'keyboardWillShowNotification' was introduced in Swift 4.2
        public class let keyboardWillShowNotification: NSNotification.Name
                         ^
    /Users/moazelshebly/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_interactive_keyboard-0.1.3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:19:114: error: 'keyboardWillHideNotification' has been renamed to 'NSNotification.Name.UIKeyboardWillHide'
            NotificationCenter.default.addObserver(self, selector: #selector(self.handleKeyboard), name: UIResponder.keyboardWillHideNotification, object: nil)
                                                                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                     NSNotification.Name.UIKeyboardWillHide
    UIKit.UIResponder:7:22: note: 'keyboardWillHideNotification' was introduced in Swift 4.2
        public class let keyboardWillHideNotification: NSNotification.Name
                         ^
    /Users/moazelshebly/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_interactive_keyboard-0.1.3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:20:115: error: 'keyboardDidShowNotification' has been renamed to 'NSNotification.Name.UIKeyboardDidShow'
            NotificationCenter.default.addObserver(self, selector: #selector(self.keyboardDidShow), name: UIResponder.keyboardDidShowNotification, object: nil)
                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                      NSNotification.Name.UIKeyboardDidShow
    UIKit.UIResponder:5:22: note: 'keyboardDidShowNotification' was introduced in Swift 4.2
        public class let keyboardDidShowNotification: NSNotification.Name
                         ^
    /Users/moazelshebly/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_interactive_keyboard-0.1.3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:21:115: error: 'keyboardDidHideNotification' has been renamed to 'NSNotification.Name.UIKeyboardDidHide'
            NotificationCenter.default.addObserver(self, selector: #selector(self.keyboardDidHide), name: UIResponder.keyboardDidHideNotification, object: nil)
                                                                                                                      ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                                                                      NSNotification.Name.UIKeyboardDidHide
    UIKit.UIResponder:9:22: note: 'keyboardDidHideNotification' was introduced in Swift 4.2
        public class let keyboardDidHideNotification: NSNotification.Name
                         ^
    /Users/moazelshebly/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_interactive_keyboard-0.1.3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:132:66: error: 'keyboardWillShowNotification' has been renamed to 'NSNotification.Name.UIKeyboardWillShow'
            let isKeyboardShowing = notification.name == UIResponder.keyboardWillShowNotification
                                                                     ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                                     NSNotification.Name.UIKeyboardWillShow
    UIKit.UIResponder:3:22: note: 'keyboardWillShowNotification' was introduced in Swift 4.2
        public class let keyboardWillShowNotification: NSNotification.Name
                         ^
    /Users/moazelshebly/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_interactive_keyboard-0.1.3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:135:59: error: 'keyboardFrameEndUserInfoKey' has been renamed to 'UIKeyboardFrameEndUserInfoKey'
                    let keyboardFrame = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as AnyObject).cgRectValue
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                              UIKeyboardFrameEndUserInfoKey
    UIKit.UIResponder:15:22: note: 'keyboardFrameEndUserInfoKey' was introduced in Swift 4.2
        public class let keyboardFrameEndUserInfoKey: String`
```

### PR DESCRIPTION
**Pull request by moazelshebly**
Solves issue #13

### CODE REVIEW

**Comment by david-shortman** [comment]
hey @moazelshebly I'm finally seeing this! I'll try to review tomorrow to make sure all is good. thanks for the contribution!

**Comment by david-shortman** [comment]
Hey @moazelshebly, I'm not able to replicate your issue.

Environment
```
$ flutter --version
Flutter 1.20.2 • channel stable • https://github.com/flutter/flutter.git
Framework • revision bbfbf1770c (13 days ago) • 2020-08-13 08:33:09 -0700
Engine • revision 9d5b21729f
Tools • Dart 2.9.1
```

I created a new project with IntelliJ Create New Project > Flutter, and then imported your fork
```
flutter_interactive_keyboard:
    git:
      url: https://github.com/moazelshebly/flutter_interactive_keyboard.git
      ref: master
```
and used the `KeyboardManagerWidget` in main.dart

Upon building, I received errors like 
```
/Volumes/Davids Passport/development/flutter/.pub-cache/git/flutter_interactive_keyboard-3569fcd2abb1d875386df1fdcc903d2384f0a0a3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:135:47: error: 'UIKeyboardFrameEndUserInfoKey' has been renamed to 'UIResponder.keyboardFrameEndUserInfoKey'
                let keyboardFrame = (userInfo[UIKeyboardFrameEndUserInfoKey] as AnyObject).cgRectValue
                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                              UIResponder.keyboardFrameEndUserInfoKey
UIKit.UIKeyboardFrameEndUserInfoKey:3:12: note: 'UIKeyboardFrameEndUserInfoKey' was obsoleted in Swift 4.2
```

When I switch to using `https://github.com/mcrovero/flutter_interactive_keyboard.git`, I am able to successfully build.

It seems we are getting conflicting messages from the Xcode compiler but I'm not sure why.

**Comment by moazelshebly** [comment]
Hey @david-shortman, thanks for your reply.

I'm not sure why we're getting different errors from Xcode but it could be that we're using different versions. The weird thing is that in both cases it's referring to Swift 4.2, which means that we're using the same version of swift.

I integrated my fork of the project in an Android studio project and it seems to be working fine.

My environment

```
flutter --version
Flutter 1.22.0-2.0.pre.161 • channel master • https://github.com/flutter/flutter.git
Framework • revision ba78539bdb (6 hours ago) • 2020-08-31 19:13:04 -0700
Engine • revision 165abef0a2
Tools • Dart 2.10.0 (build 2.10.0-77.0.dev)
```

**Comment by david-shortman** [comment]
I think I've identified the problem you were encountering.

I realized there was a difference in the error messages you were receiving when using mcrovero/flutter_keyboard_interactive versus when I tried to build your branch.

When you run `master` of this repo:
```
    /Users/moazelshebly/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_interactive_keyboard-0.1.3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:135:59: error: 'keyboardFrameEndUserInfoKey' has been renamed to 'UIKeyboardFrameEndUserInfoKey'
                    let keyboardFrame = (userInfo[UIResponder.keyboardFrameEndUserInfoKey] as AnyObject).cgRectValue
                                                              ^~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                              UIKeyboardFrameEndUserInfoKey
    UIKit.UIResponder:15:22: note: 'keyboardFrameEndUserInfoKey' was introduced in Swift 4.2
```

When I run your branch:
```
    /Users/david/development/flutter/.pub-cache/git/flutter_interactive_keyboard-3569fcd2abb1d875386df1fdcc903d2384f0a0a3/ios/Classes/SwiftFlutterInteractiveKeyboardPlugin.swift:135:47: error: 'UIKeyboardFrameEndUserInfoKey' has been renamed to 'UIResponder.keyboardFrameEndUserInfoKey'
                    let keyboardFrame = (userInfo[UIKeyboardFrameEndUserInfoKey] as AnyObject).cgRectValue
                                                  ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~
                                                  UIResponder.keyboardFrameEndUserInfoKey
    UIKit.UIKeyboardFrameEndUserInfoKey:3:12: note: 'UIKeyboardFrameEndUserInfoKey' was obsoleted in Swift 4.2
    public let UIKeyboardFrameEndUserInfoKey: String
               ^
```

Notice the difference in language. Yours is reporting that `keyboardFrameEndUserInfoKey` is **introduced** in Swift 4.2, while mine reports that `UIKeyboardFrameEndUserInfoKey` is **obsoleted** in Swift 4.2.

I believe that your Xcode environment is out of date or not targeting Swift 4.2 properly. Based on the error messages, `keyboardFrameEndUserInfoKey` and the other updated keys are in fact the correct keys for the latest version of Swift.

My latest test env:

Xcode 12.0.1 (12A7300)

Flutter 1.22.0-10.0.pre.380 • channel master • https://github.com/flutter/flutter.git
Framework • revision ec40df9576 (34 hours ago) • 2020-09-25 21:27:22 -0700
Engine • revision 3a73d073c8
Tools • Dart 2.11.0 (build 2.11.0-161.0.dev)

I am closing this PR under the assumption that I'm reading these error messages correctly.

**Pull request closed without merging**
